package net.dirbaio.protos.generator;

import com.mojang.nbt.CompoundTag;
import com.mojang.nbt.NbtIo;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import net.dirbaio.protos.Chunk;

public class DiskChunkOutput implements ChunkOutput
{
    File path;

    public DiskChunkOutput(File path)
    {
        this.path = path;
    }

    public void chunkDone(Chunk c)
    {
        try {
            c.writeTo(path);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public void generationStarted(int xMin, int zMin, int xSize, int zSize)
    {
        deleteDirectory(path);
        path.mkdirs();
        
        CompoundTag dataTag = new CompoundTag();
        dataTag.putByte("hardcore", (byte) 0);
        dataTag.putByte("mapFeatures", (byte) 0);
        dataTag.putByte("raining", (byte) 0);
        dataTag.putByte("thundering", (byte) 0);

        dataTag.putInt("GameType", 1); //0 = Survival, 1 = Creative
        dataTag.putInt("generatorVersion", 1);
        dataTag.putInt("rainTime", 0);
        dataTag.putInt("thunderTime", 0);
        dataTag.putInt("SpawnX", 128);
        dataTag.putInt("SpawnY", 256);
        dataTag.putInt("SpawnZ", 128);
        dataTag.putInt("version", 19133);
        dataTag.putLong("LastPlayed", 0);
        dataTag.putLong("RandomSeed", 0);
        dataTag.putLong("SizeOnDisk", 0);
        dataTag.putLong("Time", 0);
        dataTag.putString("generatorName", "default");
        dataTag.putString("LevelName", "Generated by Protos");

        File dataFile = new File(path, "level.dat");
        try
        {
            CompoundTag root = new CompoundTag();
            root.put("Data", dataTag);

            NbtIo.writeCompressed(root, new FileOutputStream(dataFile));
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public void generationFinished()
    {
    }

    private static boolean deleteDirectory(File path)
    {
        if (path.exists())
        {
            File[] files = path.listFiles();
            for (int i = 0; i < files.length; i++)
                if (files[i].isDirectory())
                    deleteDirectory(files[i]);
                else
                    files[i].delete();
        }
        return (path.delete());
    }

}
